# Copyright Contributors to the Open Cluster Management project
# Licensed under the Apache License 2.0

FROM quay.io/redhat-services-prod/openshift/boilerplate:image-v8.0.0 AS builder

RUN dnf -y update --allowerasing && \
dnf -y install ca-certificates tzdata git make bash && \
update-ca-trust && \
dnf clean all

ADD token-refresher /opt
WORKDIR /opt

ARG TARGETOS TARGETARCH

RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o token-refresher .

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest AS runner

COPY --from=builder /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/
COPY --from=builder /opt/token-refresher /bin/token-refresher
COPY --from=builder /opt/LICENSE /licenses/LICENSE

USER 65532:65532

ARG VERSION

LABEL vendor="Red Hat, Inc." \
  com.redhat.component="rhobs-token-refresher" \
  name="token-refresher" \
  maintainer="team-monitoring@redhat.com" \
  version="$VERSION" \
  release="$VERSION" \
  description="token-refresher is a service that 1) fetches and refreshes OAuth2 access tokens via OIDC and 2) injects OAuth2 access tokens into all outgoing requests." \
  summary="Proxy to inject OAuth2 tokens to outgoing requests"

ENTRYPOINT ["/bin/token-refresher"]
